# Generated by Django 5.2.17 on 2026-09-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته مقاله',
                'verbose_name_plural': 'دسته\u200cهای مقالات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, max_length=550, unique=True)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('doi', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='articles/pdfs/')),
                ('cover', models.ImageField(blank=True, upload_to='articles/covers/')),
                ('access', models.CharField(choices=[('open', 'آزاد'), ('external', 'نسخه خارجی')], default='open', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlecategory')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-featured', '-year', '-created_at'],
                'indexes': [models.Index(fields=['year'], name='articles_ar_year_717df9_idx'), models.Index(fields=['published'], name='articles_ar_publish_cf8385_idx')],
            },
        ),
    ]
