# Generated by Django 5.2.17 on 2026-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'در انتظار ترجمه'), ('translated', 'ترجمه شده'), ('reviewed', 'بازبینی شده')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['translation_status'], name='articles_ar_transla_ee12ba_idx'),
        ),
    ]
