# Generated by Django 5.2.17 on 2026-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_abstract_fa_article_title_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='full_text_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
