# Generated by Django 5.2.17 on 2026-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articleannotation_articlelibraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleannotation',
            name='color',
            field=models.CharField(default='amber', max_length=20),
        ),
        migrations.AddField(
            model_name='articleannotation',
            name='text_prefix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articleannotation',
            name='text_suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlelibraryitem',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlelibraryitem',
            name='reading_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
