# Generated by Django 5.2.17 on 2026-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleannotation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleannotation',
            name='rects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
