# Generated by Django 5.2.17 on 2026-09-16 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articleannotation_rects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelibraryitem',
            name='bookmarks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='articleannotation',
            index=models.Index(fields=['user', 'article'], name='articles_ar_user_id_963dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='articleannotation',
            index=models.Index(fields=['user', 'page'], name='articles_ar_user_id_354498_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelibraryitem',
            index=models.Index(fields=['user', 'status'], name='articles_ar_user_id_77ba65_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelibraryitem',
            index=models.Index(fields=['user', 'favorite'], name='articles_ar_user_id_38a171_idx'),
        ),
    ]
