# Generated by Django 5.2.17 on 2026-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlelibraryitem_bookmarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='citation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='relevance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='source_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
