# Generated by Django 5.2.17 on 2026-09-23

import books.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=books.storage.PrivateMediaStorage(), upload_to='books/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'ogg', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=books.storage.PrivateMediaStorage(), upload_to='books/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=books.storage.PrivateMediaStorage(), upload_to='chapters/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'ogg', 'wav'])]),
        ),
    ]
