# -*- coding: utf-8 -*-
"""Persian/RTL labels shared by the DANA admin.

The Django docs recommend explicit model verbose names instead of relying on
English-centric names inferred from Python class names. We also normalize
field labels here so list/form/table headers remain Persian without requiring
database migrations.
"""
from django.apps import apps

APP_LABELS = {
    'accounts': 'حساب‌های کاربری',
    'analytics': 'تحلیل و آمار',
    'articles': 'مقالات',
    'books': 'کتاب‌ها',
    'gamification': 'بازی‌وارسازی',
    'notifications': 'اعلان‌ها',
    'reader': 'مطالعه',
    'shop': 'فروشگاه',
    'support': 'پشتیبانی',
    'api': 'رابط برنامه‌نویسی',
}

MODEL_LABELS = {
    'Device': 'دستگاه‌ها',
    'OTPCode': 'کدهای یکبارمصرف',
    'UserSession': 'نشست‌های کاربران',
    'User': 'کاربران',
    'Author': 'نویسندگان',
    'Book': 'کتاب‌ها',
    'Category': 'دسته‌بندی‌ها',
    'Chapter': 'فصل‌ها',
    'Level': 'سطح‌ها',
    'MediaAsset': 'رسانه‌ها',
    'Badge': 'نشان‌ها',
    'GamificationLevel': 'سطح‌های بازی‌وارسازی',
    'HallOfFameRecord': 'تالار افتخار',
    'Mission': 'مأموریت‌ها',
    'PointLedger': 'دفتر امتیازها',
    'UserBadge': 'نشان‌های کاربران',
    'UserMission': 'مأموریت‌های کاربران',
    'UserStreak': 'تداوم فعالیت کاربران',
    'XPEvent': 'رویدادهای XP',
    'Order': 'سفارش‌ها',
    'OrderItem': 'اقلام سفارش',
    'Coupon': 'کدهای تخفیف',
    'CartItem': 'سبدهای خرید',
    'Entitlement': 'دسترسی کتاب‌ها',
    'Referral': 'معرفی دوستان',
    'WalletTransaction': 'تراکنش‌های کیف پول',
    'CheckoutRequest': 'درخواست‌های پرداخت',
    'Payment': 'پرداخت‌ها',
    'Ticket': 'تیکت‌ها',
    'TicketMessage': 'پیام‌های تیکت',
    'Review': 'نقد و بررسی‌ها',
    'ReadingProgress': 'پیشرفت مطالعه',
    'Bookmark': 'نشانک‌ها',
    'Note': 'یادداشت‌ها',
    'ProblemReport': 'گزارش مشکلات',
    'SavedWord': 'واژه‌های ذخیره‌شده',
    'Notification': 'اعلان‌ها',
    'EmailLog': 'گزارش‌های ایمیل',
    'PushSubscription': 'اشتراک‌های اعلان فوری',
    'Event': 'رویدادها',
    'Article': 'مقالات',
    'ArticleCategory': 'دسته‌های مقالات',
    'ArticleLibraryItem': 'کتابخانه مقالات',
    'ArticleAnnotation': 'حاشیه‌نویسی مقالات',
}

FIELD_LABELS = {
    'id': 'شناسه',
    'user': 'کاربر',
    'username': 'نام کاربری',
    'phone': 'شماره موبایل',
    'email': 'ایمیل',
    'first_name': 'نام',
    'last_name': 'نام خانوادگی',
    'password': 'رمز عبور',
    'is_staff': 'مدیر/کارمند',
    'is_superuser': 'دسترسی کامل',
    'is_active': 'فعال',
    'is_deactivated': 'غیرفعال‌شده',
    'date_joined': 'تاریخ عضویت',
    'last_login': 'آخرین ورود',
    'avatar': 'تصویر کاربر',
    'wallet_balance': 'موجودی کیف پول',
    'wallet_topup': 'شارژ کیف پول',
    'xp': 'تجربه (XP)',
    'points': 'امتیاز',
    'purchase_points': 'امتیاز خرید',
    'study_points': 'امتیاز مطالعه',
    'leaderboard_public': 'نمایش در رتبه‌بندی',
    'referral_code': 'کد دعوت',
    'terms_accepted_at': 'زمان پذیرش قوانین',
    'name': 'نام',
    'title': 'عنوان',
    'title_fa': 'عنوان فارسی',
    'slug': 'نشانی یکتا',
    'bio': 'معرفی',
    'description': 'توضیحات',
    'summary': 'خلاصه',
    'category': 'دسته‌بندی',
    'parent': 'دسته والد',
    'author': 'نویسنده',
    'authors': 'نویسندگان',
    'book': 'کتاب',
    'books': 'کتاب‌ها',
    'level': 'سطح',
    'order': 'ترتیب',
    'min_xp': 'حداقل XP',
    'price': 'قیمت',
    'old_price': 'قیمت قبلی',
    'cover': 'جلد',
    'pdf': 'فایل PDF',
    'audio': 'فایل صوتی',
    'text': 'متن',
    'full_text': 'متن کامل',
    'full_text_fa': 'متن کامل فارسی',
    'abstract': 'چکیده',
    'abstract_fa': 'چکیده فارسی',
    'visibility': 'سطح دسترسی',
    'access': 'نوع دسترسی',
    'access_password': 'رمز دسترسی',
    'status': 'وضعیت',
    'publish_at': 'زمان انتشار',
    'published': 'منتشر شده',
    'featured': 'ویژه',
    'preview_percent': 'درصد پیش‌نمایش',
    'created_at': 'تاریخ ایجاد',
    'updated_at': 'آخرین ویرایش',
    'downloads': 'تعداد دریافت',
    'year': 'سال',
    'journal': 'نشریه',
    'doi': 'DOI',
    'source_provider': 'منبع',
    'external_id': 'شناسه منبع',
    'citation_count': 'تعداد استناد',
    'relevance_score': 'امتیاز ارتباط',
    'source_url': 'نشانی منبع',
    'pdf_url': 'نشانی PDF',
    'translation_status': 'وضعیت ترجمه',
    'translated_at': 'زمان ترجمه',
    'translation_hash': 'شناسه نسخه ترجمه',
    'kind': 'نوع',
    'file': 'فایل',
    'duration': 'مدت',
    'code': 'کد',
    'percent': 'درصد تخفیف',
    'amount': 'مبلغ',
    'capacity': 'ظرفیت',
    'used': 'مصرف‌شده',
    'min_order': 'حداقل مبلغ سفارش',
    'expires_at': 'زمان انقضا',
    'active': 'فعال',
    'subtotal': 'جمع اقلام',
    'discount': 'تخفیف',
    'tax': 'مالیات',
    'total': 'مبلغ نهایی',
    'tracking_code': 'کد پیگیری',
    'gift_to': 'گیرنده هدیه',
    'order': 'سفارش',
    'order_item': 'قلم سفارش',
    'granted_at': 'زمان اعطای دسترسی',
    'type': 'نوع تراکنش',
    'reason': 'شرح',
    'balance_before': 'موجودی قبل',
    'balance_after': 'موجودی بعد',
    'reference': 'مرجع',
    'provider': 'درگاه/ارائه‌دهنده',
    'authority': 'کد Authority',
    'callback_payload': 'اطلاعات بازگشتی درگاه',
    'idempotency_key': 'کلید جلوگیری از تکرار',
    'inviter': 'دعوت‌کننده',
    'invitee': 'دعوت‌شده',
    'rewarded': 'پاداش داده شده',
    'rating': 'امتیاز',
    'admin_score': 'امتیاز مدیر',
    'admin_reply': 'پاسخ مدیر',
    'approved': 'تأیید شده',
    'progress': 'پیشرفت',
    'current_page': 'صفحه فعلی',
    'current_chapter': 'فصل فعلی',
    'seconds': 'ثانیه مطالعه',
    'audio_seconds': 'ثانیه صوت',
    'page': 'صفحه',
    'body': 'متن پیام',
    'subject': 'موضوع',
    'priority': 'اولویت',
    'assigned_to': 'مسئول رسیدگی',
    'category': 'دسته‌بندی',
    'read_at': 'زمان خواندن',
    'endpoint': 'نشانی اعلان',
    'p256dh': 'کلید عمومی',
    'auth': 'کلید احراز',
    'point_type': 'نوع امتیاز',
    'revoked': 'باطل‌شده',
    'source': 'منبع',
    'period': 'دوره',
    'target': 'هدف',
    'xp_reward': 'پاداش XP',
    'study_points_reward': 'پاداش امتیاز مطالعه',
    'completed_at': 'زمان تکمیل',
    'period_key': 'شناسه دوره',
    'current_days': 'روزهای فعلی',
    'longest_days': 'بیشترین تداوم',
    'last_activity_date': 'آخرین فعالیت',
    'value': 'مقدار',
    'metadata': 'اطلاعات تکمیلی',
    'email': 'ایمیل',
    'read_at': 'زمان مشاهده',
    'purpose': 'کاربرد',
    'expires_at': 'زمان انقضا',
    'attempts': 'تعداد تلاش',
    'used': 'مصرف شده',
    'last_seen': 'آخرین مشاهده',
    'session_key': 'شناسه نشست',
    'device': 'دستگاه',
    'ip': 'نشانی IP',
    'user_agent': 'مرورگر/دستگاه',
    'selected_text': 'متن انتخاب‌شده',
    'note': 'یادداشت',
    'color': 'رنگ',
    'page': 'صفحه',
    'text_prefix': 'متن قبل',
    'text_suffix': 'متن بعد',
    'rects': 'مختصات',
    'last_position': 'آخرین موقعیت',
    'reading_seconds': 'زمان مطالعه',
    'last_read_at': 'آخرین مطالعه',
    'favorite': 'موردعلاقه',
    'bookmarks': 'نشانک‌ها',
    'word': 'واژه',
    'normalized_word': 'واژه نرمال‌شده',
    'source_language': 'زبان مبدأ',
    'meaning_fa': 'معنی فارسی',
    'pronunciation_fa': 'تلفظ فارسی',
    'example_en': 'مثال انگلیسی',
    'last_reviewed': 'آخرین مرور',
    'review_count': 'تعداد مرور',
    'email': 'ایمیل',
    'content_type': 'نوع محتوا',
    'object_id': 'شناسه شیء',
    'object_repr': 'نمایش شیء',
    'action_time': 'زمان عملیات',
    'action_flag': 'نوع عملیات',
    'change_message': 'شرح تغییر',
}

CHOICE_LABELS = {
    'pending': 'در انتظار',
    'paid': 'پرداخت‌شده',
    'cancelled': 'لغوشده',
    'gift': 'هدیه',
    'successful': 'موفق',
    'failed': 'ناموفق',
    'refunded': 'برگشت‌خورده',
    'wallet': 'کیف پول',
    'credit': 'واریز',
    'debit': 'برداشت',
    'refund': 'بازگشت وجه',
    'reward': 'پاداش',
    'open': 'باز',
    'in_progress': 'در حال رسیدگی',
    'waiting': 'در انتظار پاسخ',
    'resolved': 'حل‌شده',
    'closed': 'بسته',
    'low': 'کم',
    'normal': 'عادی',
    'high': 'زیاد',
    'urgent': 'فوری',
    'draft': 'پیش‌نویس',
    'scheduled': 'زمان‌بندی‌شده',
    'published': 'منتشرشده',
    'public': 'عمومی',
    'private': 'خصوصی',
    'password': 'رمزدار',
    'daily': 'روزانه',
    'weekly': 'هفتگی',
    'monthly': 'ماهانه',
    'credit': 'واریز',
    'debit': 'برداشت',
}

for app_config in apps.get_app_configs():
    if app_config.label in APP_LABELS:
        app_config.verbose_name = APP_LABELS[app_config.label]

for model in apps.get_models():
    label = MODEL_LABELS.get(model.__name__)
    if label:
        model._meta.verbose_name = label.rstrip('ها') if label.endswith('ها') else label
        model._meta.verbose_name_plural = label
    for field in model._meta.fields:
        if field.name in FIELD_LABELS:
            field.verbose_name = FIELD_LABELS[field.name]
        if getattr(field, 'choices', None):
            field.choices = [
                (value, CHOICE_LABELS.get(str(value), label))
                for value, label in field.choices
            ]
